#include <map>
#include <string>
#include <fstream>
#include <iostream>

std::string filepath_to_varname(const std::string& filepath);

void generate_header(const std::string& path, const std::string& classname, const std::map<std::string, std::string>& files)
{
  std::ofstream header;

  header.open(path + ".hpp");
  header << "#pragma once" << std::endl;
  header << "#include <crails/request_handlers/builtin_assets.hpp>" << std::endl;
  header << std::endl;
  header << "// Generated by crails-builtin-assets" << std::endl;
  header << "class " << classname << " : public Crails::BuiltinAssets" << std::endl;
  header << '{' << std::endl;
  header << "public:" << std::endl;
  header << "  " << classname << "();" << std::endl;
  header << std::endl;
  for (const auto& file : files)
    header << "  static const char* " << filepath_to_varname(file.second) << ';' << std::endl;
  header << "};" << std::endl;
  header.close();
}
