libs =
import libs += libboost-program-options%lib{boost_program_options}
import libs += libboost-filesystem%lib{boost_filesystem}
import libs += libcrails-cli%lib{crails-cli}
import libs += libcrails-semantics%lib{crails-semantics}

exe{crails-assets}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
